#------------------------------------------
 #Problem 2 - Even Fibonacci numbers
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#------------------------------------------

a=0
b=1
c=0
terms=0
Fibonacci=[0]
while max(Fibonacci)<4000000:
    Fibonacci.append(a+b)
    c=a+b
    a=b
    b=c
print(Fibonacci)

if max(Fibonacci) > 4000000:
    Fibonacci.remove(max(Fibonacci))
print(Fibonacci)

length=len(Fibonacci) # gives the length of the list as an integer
for i in range(length):
    print(i, " === ", Fibonacci[i])
    if int(Fibonacci[i])%2==0: # make a list membber into
        terms=terms+int(Fibonacci[i])
        print(terms)
